### ISSUE TITLE
Allow Details on click for Discovery Activity

### ISSUE THREAD

**Issue by kevinchristianson** [PickFlicks/App#6]

**Comment by kevinchristianson** [comment]
Clicking on Discover cards should
Tricky Part: What happens if they add to watch list on details page?

**Comment by kevinchristianson** [comment]
An alternative is redesigning the cards so that they include more details. This would be nice as I think the discover activity should be streamlined and focus on browsing films. We'll need to know how much information people need before adding a movie to their watchlist and then try to design cards that have most or all of it, which might prove difficult to do well.

**Comment by ritvikkar** [comment]
@kevinchristianson is this closed?

**Comment by kevinchristianson** [comment]
Yup!
