### ISSUE TITLE
App Logo/Icons

### ISSUE THREAD

**Issue by kevinchristianson** [PickFlicks/App#8]
- [x] Logo for App
- [x] Icon for Discover Activity
- [x] Icon for adding to watch list (heart doesn't quite fit)

**Comment by kevinchristianson** [comment]
We should comply with TMDb's terms of use:
'''
You shall use the TMDb logo to identify your use of the TMDb APIs.

You shall place the following notice prominently on your application: "This product uses the TMDb API but is not endorsed or certified by TMDb."

Any use of the TMDb logo in your application shall be less prominent than the logo or mark that primarily describes the application and your use of the TMDb logo shall not imply any endorsement by TMDb.
'''

**Comment by ritvikkar** [comment]
![movie details - liked](https://user-images.githubusercontent.com/17035034/45137719-bfefb500-b15e-11e8-9a0d-a1ffc1f3258e.png)
![movie details](https://user-images.githubusercontent.com/17035034/45137720-c0884b80-b15e-11e8-98dc-f709ab3e9611.png)
![movie tile](https://user-images.githubusercontent.com/17035034/45137721-c0884b80-b15e-11e8-8679-70ecb0fe3036.png)

**Comment by ritvikkar** [comment]
- [ ] Adhere to the movie db policy (I think I quoted it in the issue). 
- [ ] The FAB isn't the best design since it covers up the movie posters and the image we use, while cool, doesn't really tell the user what to expect before clicking it
